name: Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call:


jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Building images
        id: images
        run: make image

      - name: Tests
        id: tests
        run: make test

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
